version: "3.9"

services:
  bot:
    build:
      context: .
      target: runner
    image: jacoblincool/chatgpt-agent
    container_name: chatgpt-agent
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./store:/app/.store
